# Generated by Django 3.0.3 on 2020-02-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calenderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleevent',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='scheduleevent',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='scheduleevent',
            name='description',
        ),
    ]
